### ISSUE TITLE
Typo in the first line of README.md

### ISSUE THREAD

**Issue by shafferz** [Allegheny-Computer-Science-203-S2019/cs203-S2019-practical3-starter#2]
The first line of `README.md` claims that this is the starter repository for Practical 2. This, however, is the repository for Practical 3. I believe this is a typo from copy/paste issues.

**Comment by gkapfham** [comment]
Hello @shafferz, thanks for reporting this issue. I have resolved it now. If you notice any additional mistakes, please let me know and I will handle them as well.
